echo sonar.projectKey=tuning-project > sonar-project.properties
echo sonar.projectName=Tuning >> sonar-project.properties
echo sonar.sources=. >> sonar-project.properties
echo sonar.exclusions=**/tests/**,**/static/** >> sonar-project.properties
echo sonar.python.version=3.13.1 >> sonar-project.properties
echo sonar.sourceEncoding=UTF-8 >> sonar-project.properties
echo sonar.host.url=http://localhost:9000 >> sonar-project.properties
echo sonar.login=sqp_d78afed5b028f07e4c31042561756a872d5d7766 >> sonar-project.properties

##Análisis•Tuning: sqp_d78afed5b028f07e4c31042561756a872d5d7766


### Iniciar el servidor de SonarQube
##cd "F:\Users\Plan Study Majora\sonarqube-25.4.0.105899"
## .\bin\windows-x86-64\StartSonar.bat

""" Accede a http://localhost:9000, inicia sesión (admin/admin) y cambia la contraseña.
    Crea un nuevo proyecto en SonarQube y genera un token de acceso.
    Copia el token generado y pégalo en el archivo sonar-project.properties.
    Asegúrate de que el servidor de SonarQube esté en ejecución antes de iniciar el escáner.
"""

### Iniciar el escaner de SonarQube en el proyecto
##  cd "F:\Users\Plan Study Majora\Tuning"
##>> "F:\Users\Plan Study Majora\sonar-scanner-7.1.0.4889-windows-x64/bin/sonar-scanner.bat"